### ISSUE TITLE
Integrate automated testing

### ISSUE THREAD

**Issue by mariobehling** [loklak/asksusi_messenger#4]
There are number of automated test that can be integrated. Which ones are suitable for the technologies used in the project? 

A list is here https://github.com/integrations

Please propose and integrate more tests e.g.
* [x] https://www.codacy.com
* [x] Travis
* [x] Cirlce CI
* [x] Code Climate
* [x] https://codecov.io
* [x] <strike>https://coveralls.io</strike>
* [x] <strike>https://gemnasium.com</strike>

**Comment by jig08** [comment]
A suggestion:  [semaphoreci.com](https://semaphoreci.com/)

**Comment by sudheesh001** [comment]
Facing issues with code climate, coveralls and codecov do the same thing, I don't think we need multiple things running the same coverages.

<img width="1440" alt="screen shot 2016-07-22 at 3 43 31 pm" src="https://cloud.githubusercontent.com/assets/4545925/17054126/103e3d96-5023-11e6-8d04-525b4eb73ee1.png">

**Comment by daminisatya** [comment]
@sudheesh001 Yes, there will be a lot of confusion. What you have integrated so far is good to go.
